all: Unbroken

clean:
	rm Unbroken
	rm Double
	rm Multiple

Unbroken: Unbroken.c
	gcc -Wall -o Unbroken Unbroken.c

Double: Double.c
	gcc -Wall -o Double Double.c

Multiple: Multiple.c
	gcc -Wall -o Multiple Multiple.c
